#!/bin/sh

echo "***** Checking Commit Message ******"

# shellcheck disable=SC2320
status=$?


message="$(cat $1)"
regex_commit_format='(^GH-[0-9]{1,5}): \[(ADD|REMOVE|CHANGE|FIX|WIP|REFACTOR|TEST)\] [A-Z]'
error_msg="Commit not allowed, message should have an issue number, a tag, and start with a capital letter  "

# shellcheck disable=SC2039
# shellcheck disable=SC3010
if ! [[ $message =~ $regex_commit_format ]]; then
    echo "$error_msg" >&2
    echo "Example: GH-2: [ADD] Message"
    echo "The rules are:"
    echo "$regex_commit_format"
    exit 1
else
    echo "Commit is successful"
fi


echo "***** Done ******"

exit $status